/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const AccountForm: React.FC = () => {
  return (
    <form className="flex flex-col self-center p-6 mt-2 max-w-full text-sm bg-white rounded-md border border-solid border-slate-200 w-[400px] max-md:px-5">
      <p className="leading-5 text-slate-500">
        Make changes to your account here. Click save when you're done.
      </p>
      <label htmlFor="name" className="mt-4 font-medium text-slate-900">
        Name
      </label>
      <input
        id="name"
        type="text"
        className="px-3 py-2 mt-1.5 bg-white rounded-md border border-solid border-slate-300 leading-[143%] text-slate-900 max-md:pr-5"
        defaultValue="Pietro Schirano"
      />
      <label htmlFor="username" className="mt-2 font-medium text-slate-900">
        Username
      </label>
      <input
        id="username"
        type="text"
        className="px-3 py-2 mt-1.5 whitespace-nowrap bg-white rounded-md border border-solid border-slate-300 leading-[143%] text-slate-900 max-md:pr-5"
        defaultValue="@skirano"
      />
      <button
        type="submit"
        className="self-start px-4 py-2 mt-4 font-medium leading-6 text-white rounded-md bg-slate-900"
      >
        Save changes
      </button>
    </form>
  );
};

export default AccountForm;