/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const TabPanel: React.FC = () => {
  return (
    <nav className="flex self-start p-1.5 mt-16 ml-40 text-sm font-medium leading-5 whitespace-nowrap rounded-md bg-slate-100 max-md:mt-10 max-md:ml-2.5">
      <button className="px-3 py-1.5 bg-white rounded text-slate-900">Account</button>
      <button className="px-3 py-1.5 rounded text-slate-700">Password</button>
    </nav>
  );
};

export default TabPanel;