/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import TabPanel from './TabPanel';
import AccountForm from './AccountForm';

interface TabsProps {
  title: string;
  description: string;
}

const Tabs: React.FC<TabsProps> = ({ title, description }) => {
  return (
    <main className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <Header title={title} description={description} />
      <hr className="shrink-0 mt-8 h-px border border-solid bg-slate-200 border-slate-200 max-md:max-w-full" />
      <TabPanel />
      <AccountForm />
    </main>
  );
};

export default Tabs;