/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BlockQuote: React.FC = () => {
  return (
    <blockquote className="flex gap-5 mt-8 text-base leading-6 rounded-none text-slate-900 max-md:flex-wrap">
      <div className="shrink-0 w-0.5 h-12 border-2 border-solid border-neutral-200" />
      <p className="flex-auto my-auto italic max-md:max-w-full">
        "After all," he said, "everyone enjoys a good joke, so it's only fair
        that they should pay for the privilege."
      </p>
    </blockquote>
  );
};

export default BlockQuote;
