/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex max-md:flex-wrap">
      <div className="flex flex-col flex-1 max-md:max-w-full">
        <h1 className="text-3xl font-semibold tracking-tight leading-9 text-slate-900 max-md:max-w-full">
          Typography
        </h1>
        <p className="mt-4 text-xl leading-7 text-slate-600 max-md:max-w-full">
          Styles for headings, paragraphs, lists...etc
        </p>
      </div>
      <div className="flex flex-col justify-center self-start text-sm font-medium leading-6 text-white rounded-md">
        <button className="px-3.5 py-2 rounded-md bg-slate-900">
          View docs
        </button>
      </div>
    </header>
  );
};

export default Header;
