/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InlineCode: React.FC = () => {
  return (
    <code className="self-start px-1 py-1 mt-8 text-sm font-bold leading-5 text-black whitespace-nowrap rounded bg-slate-100">
      @radix-ui/react-alert-dialog
    </code>
  );
};

export default InlineCode;
