/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Large: React.FC = () => {
  return (
    <p className="self-start mt-8 text-lg font-semibold leading-7 text-black">
      Are you sure absolutely sure?
    </p>
  );
};

export default Large;
