/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Lead: React.FC = () => {
  return (
    <p className="mt-8 text-xl leading-7 text-slate-900 w-[666px] max-md:max-w-full">
      A modal dialog that interrupts the user with important content and expects
      a response.
    </p>
  );
};

export default Lead;
