/**
 * This code was generated by Builder.io.
 */
import React from "react";

const listItems = [
  "1st level of puns: 5 gold coins",
  "2nd level of jokes: 10 gold coins",
  "3rd level of one-liners : 20 gold coins",
];

const List: React.FC = () => {
  return (
    <ul className="self-start mt-8 text-base leading-6 text-slate-900">
      {listItems.map((item, index) => (
        <li key={index} className={index > 0 ? "mt-2" : ""}>
          {item}
        </li>
      ))}
    </ul>
  );
};

export default List;
