/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Divider from "./Divider";

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

const Section: React.FC<SectionProps> = ({ title, children }) => {
  return (
    <>
      <section className="mt-14 max-md:mt-10 max-md:max-w-full">
        <h2 className="text-3xl font-semibold tracking-tight leading-9 text-slate-900">
          {title}
        </h2>
        {children}
      </section>
      <Divider />
    </>
  );
};

export default Section;
