/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Small: React.FC = () => {
  return (
    <label
      htmlFor="email"
      className="self-start mt-8 text-sm font-medium leading-4 text-black"
    >
      Email address
    </label>
  );
};

export default Small;
