/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Subtle: React.FC = () => {
  return (
    <p className="self-start mt-8 text-sm leading-5 text-slate-500">
      Enter your email address.
    </p>
  );
};

export default Subtle;
