/**
 * This code was generated by Builder.io.
 */
import React from "react";

const tableData = [
  { treasury: "Empty", happiness: "Overflowing" },
  { treasury: "Modest", happiness: "Satisfied" },
  { treasury: "Empty", happiness: "Overflowing" },
];

const Table: React.FC = () => {
  return (
    <table className="mt-8 text-base leading-6 text-slate-900 max-md:max-w-full">
      <thead>
        <tr className="font-bold">
          <th className="px-4 py-2 bg-white border border-solid border-slate-200 max-md:pr-5 max-md:max-w-full">
            King's Treasury
          </th>
          <th className="px-4 py-2 bg-white border border-solid border-slate-200 max-md:pr-5 max-md:max-w-full">
            People's happiness
          </th>
        </tr>
      </thead>
      <tbody>
        {tableData.map((row, index) => (
          <tr
            key={index}
            className={index % 2 === 1 ? "bg-slate-100" : "bg-white"}
          >
            <td className="px-4 py-2 border border-solid border-slate-200 max-md:pr-5 max-md:max-w-full">
              {row.treasury}
            </td>
            <td className="px-4 py-2 border border-solid border-slate-200 max-md:pr-5 max-md:max-w-full">
              {row.happiness}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
};

export default Table;
