/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Section from "./Section";
import Divider from "./Divider";
import BlockQuote from "./BlockQuote";
import Table from "./Table";
import List from "./List";
import InlineCode from "./InlineCode";
import Lead from "./Lead";
import Large from "./Large";
import Small from "./Small";
import Subtle from "./Subtle";

const Typography: React.FC = () => {
  return (
    <main className="flex flex-col px-8 pt-8 pb-16 bg-white max-md:px-5">
      <Header />
      <Divider />
      <Section title="h1">
        <h1 className="mt-8 text-5xl font-extrabold tracking-tight leading-10 text-slate-900 max-md:max-w-full max-md:text-4xl max-md:leading-10">
          Taxing Laughter: The Joke Tax <br /> Chronicles
        </h1>
      </Section>
      <Section title="h2">
        <h2 className="mt-8 text-3xl font-semibold tracking-tight leading-9 text-slate-900 max-md:max-w-full">
          The People of the Kingdom
        </h2>
      </Section>
      <Section title="h3">
        <h3 className="mt-8 text-2xl font-semibold tracking-normal leading-8 text-slate-900 max-md:max-w-full">
          The Joke Tax
        </h3>
      </Section>
      <Section title="h4">
        <h4 className="self-start mt-8 text-xl font-semibold tracking-normal leading-7 text-slate-900">
          People stopped telling jokes
        </h4>
      </Section>
      <Section title="p">
        <p className="mt-8 text-base leading-7 text-slate-900 max-md:max-w-full">
          The king, seeing how much happier his subjects were, realized the
          error of his ways and repealed the joke tax.
        </p>
      </Section>
      <Section title="blockquote">
        <BlockQuote />
      </Section>
      <Section title="table">
        <Table />
      </Section>
      <Section title="list">
        <List />
      </Section>
      <Section title="inline code">
        <InlineCode />
      </Section>
      <Section title="lead">
        <Lead />
      </Section>
      <Section title="large">
        <Large />
      </Section>
      <Section title="small">
        <Small />
      </Section>
      <Section title="subtle">
        <Subtle />
      </Section>
    </main>
  );
};

export default Typography;
