/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Divider from "./Divider";

interface AspectRatioProps {
  imageUrl: string;
}

const AspectRatio: React.FC<AspectRatioProps> = ({ imageUrl }) => {
  return (
    <section className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <Header
        title="Aspect Ratio"
        description="Displays content within a desired ratio."
      />
      <Divider />
      <img
        loading="lazy"
        src={imageUrl}
        alt="Aspect ratio demonstration"
        className="self-center mt-16 w-full rounded-md aspect-[1.79] max-w-[690px] max-md:mt-10 max-md:max-w-full"
      />
    </section>
  );
};

export default AspectRatio;