/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ColorSwatchProps {
  shade: string;
  hex: string;
}

const ColorSwatch: React.FC<ColorSwatchProps> = ({ shade, hex }) => {
  return (
    <div className="flex flex-col py-px">
      <div className={`shrink-0 h-10 rounded bg-slate-${shade}`} />
      <div className="mt-2 text-black">{shade}</div>
      <div className="leading-[133%] text-slate-400">{hex}</div>
    </div>
  );
};

export default ColorSwatch;
