/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ColorSwatch from "./ColorSwatch";

interface ColorPaletteProps {
  colorName: string;
  colors: Array<{
    shade: string;
    hex: string;
  }>;
}

const ColorPalette: React.FC<ColorPaletteProps> = ({ colorName, colors }) => {
  return (
    <div className="flex gap-4 self-center mt-16 font-medium whitespace-nowrap max-md:flex-wrap max-md:mt-10">
      <div className="my-auto text-sm leading-6 text-black">{colorName}</div>
      <div className="flex gap-2 text-xs max-md:flex-wrap">
        {colors.map((color, index) => (
          <ColorSwatch key={index} shade={color.shade} hex={color.hex} />
        ))}
      </div>
    </div>
  );
};

export default ColorPalette;
