/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  const links = ['Blog', 'Docs', 'Source'];

  return (
    <footer className="flex flex-col items-center mt-16 max-md:mt-10">
      <h2 className="text-sm font-medium leading-4 text-black">Radix Primitives</h2>
      <p className="mt-1 text-sm leading-5 text-slate-700">
        An open-source UI component library.
      </p>
      <hr className="shrink-0 mt-4 max-w-full h-px border border-solid bg-slate-200 border-slate-200 w-[252px]" />
      <nav className="flex gap-4 justify-between mt-4 max-w-full text-sm text-black whitespace-nowrap w-[252px]">
        {links.map((link, index) => (
          <a key={index} href="#" className="text-black">
            {link}
          </a>
        ))}
      </nav>
    </footer>
  );
};

export default Footer;