/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HtDr5VT1wsp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";
import Link from "next/link"
import React from "react";

export function galleryGridHv() {
  return (
    <div className="bg-gray-950 text-white p-4 sm:p-6 md:p-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-2xl font-bold mb-6">Interactive Gallery Grid</h1>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 sm:gap-6 md:gap-8">
          <div className="relative group overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View Gallery</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={400}
              height={400}
              className="w-full h-64 object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gray-900/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
              <div className="grid gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View Gallery</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={400}
              height={400}
              className="w-full h-64 object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gray-900/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
              <div className="grid gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View Gallery</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={400}
              height={400}
              className="w-full h-64 object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gray-900/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
              <div className="grid gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View Gallery</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={400}
              height={400}
              className="w-full h-64 object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gray-900/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
              <div className="grid gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View Gallery</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={400}
              height={400}
              className="w-full h-64 object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-gray-900/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
              <div className="grid gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Subgallery Item"
                  width={200}
                  height={200}
                  className="w-full h-32 object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
export default galleryGridHv;