/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IRLqP49SygD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import React from "react";

export function Gallery() {
  return (
    <section className="w-full py-12 md:py-16 lg:py-20 dark:bg-gray-950">
      <div className="container grid gap-6 px-4 md:px-6">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={300}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:bg-black/80 transition-colors duration-300 ease-in-out text-white p-6 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Gallery Item 1</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 1"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 2"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 3"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
              </div>
            </div>
            <div />
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={300}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:bg-black/80 transition-colors duration-300 ease-in-out text-white p-6 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Gallery Item 2</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 1"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 2"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 3"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
              </div>
            </div>
            <div />
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={300}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:bg-black/80 transition-colors duration-300 ease-in-out text-white p-6 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Gallery Item 3</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 1"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 2"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 3"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
              </div>
            </div>
            <div />
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={300}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:bg-black/80 transition-colors duration-300 ease-in-out text-white p-6 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Gallery Item 4</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 1"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 2"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 3"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
              </div>
            </div>
            <div />
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Gallery Item"
              width={300}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:bg-black/80 transition-colors duration-300 ease-in-out text-white p-6 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Gallery Item 5</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 1"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 2"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
                <div className="relative overflow-hidden rounded-lg">
                  <img
                    src="/placeholder.svg"
                    alt="Subgallery Item 3"
                    width={100}
                    height={133}
                    className="object-cover w-full aspect-[3/4] transition-all duration-300 ease-in-out group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-l from-black/70 to-transparent" />
                </div>
              </div>
            </div>
            <div />
          </div>
        </div>
      </div>
    </section>
  )
}

function MaximizeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  )
}
export default Gallery;