/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wK4crzOqr7e
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { useEffect } from 'react'
import { useSwipeable } from 'react-swipeable'


export function Main() {
  return (
    <div className="w-full h-screen overflow-auto scroll-smooth">
      <section className="w-full h-screen relative">
        <div className="absolute inset-0 z-0">
          <video src="/video1.mp4" autoPlay loop muted className="w-full h-full object-cover" />
        </div>
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-black/50 flex flex-col items-center justify-center text-white px-4 text-center">
          <h1 className="text-4xl font-bold mb-4">Welcome</h1>
          <p className="text-lg mb-8">Explore</p>
          <div />
        </div>
      </section>
      <section className="w-full h-screen relative">
        <div className="absolute inset-0 z-0">
          <img src="/placeholder.svg" alt="Background Image" fill className="object-cover" />
        </div>
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-black/50 flex flex-col items-center justify-center text-white px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Discover Our Products</h2>
          <p className="text-lg mb-8">Scroll to explore our diverse offerings</p>
          <div />
        </div>
      </section>
      <section className="w-full h-screen relative">
        <div className="absolute inset-0 z-0">
          <div className="grid grid-cols-2 gap-4 h-full">
            <div className="relative">
              <img src="/placeholder.svg" alt="Background Image" fill className="object-cover" />
            </div>
            <div className="relative">
              <video src="/video2.mp4" autoPlay loop muted className="w-full h-full object-cover" />
            </div>
          </div>
        </div>
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-black/50 flex flex-col items-center justify-center text-white px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Explore Our Services</h2>
          <p className="text-lg mb-8">Swipe horizontally to view more</p>
          <div>
            <div className="flex gap-4">
              <div />
              <div />
              <div />
              <div />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full h-screen relative">
        <div className="absolute inset-0 z-0">
          <div className="grid grid-cols-3 gap-4 h-full">
            <div className="relative">
              <img src="/placeholder.svg" alt="Background Image" fill className="object-cover" />
            </div>
            <div className="relative">
              <img src="/placeholder.svg" alt="Background Image" fill className="object-cover" />
            </div>
            <div className="relative">
              <img src="/placeholder.svg" alt="Background Image" fill className="object-cover" />
            </div>
          </div>
        </div>
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-black/50 flex flex-col items-center justify-center text-white px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Our Gallery</h2>
          <p className="text-lg mb-8">Swipe horizontally to view more</p>
          <div>
            <div className="flex gap-4">
              <div />
              <div />
              <div />
              <div />
            </div>
          </div>
        </div>
      </section>
      <section className="w-full h-screen relative">
        <div className="absolute inset-0 z-0">
          <video src="/video3.mp4" autoPlay loop muted className="w-full h-full object-cover" />
        </div>
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-black/50 flex flex-col items-center justify-center text-white px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Contact Us</h2>
          <p className="text-lg mb-8">Get in touch for more information</p>
          <div />
        </div>
      </section>
    </div>
  )
}
export default Main;