/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DimensionInput from './DimensionInput';

interface Dimension {
  label: string;
  value: string;
}

const dimensions: Dimension[] = [
  { label: 'Width', value: '100%' },
  { label: 'Max. width', value: '300px' },
  { label: 'Height', value: '25px' },
  { label: 'Max. height', value: 'none' },
];

const DimensionsForm: React.FC = () => {
  return (
    <form className="flex flex-col self-center p-4 mt-16 w-80 max-w-full text-sm bg-white rounded-md border border-solid shadow-sm border-slate-200 max-md:mt-10">
      <h2 className="text-base font-medium text-black">Dimensions</h2>
      <p className="mt-2 leading-[143%] text-slate-400">
        Set the dimensions for the layer.
      </p>
      {dimensions.map((dimension, index) => (
        <DimensionInput key={index} label={dimension.label} value={dimension.value} />
      ))}
    </form>
  );
};

export default DimensionsForm;