/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Divider: React.FC = () => {
  return (
    <hr className="shrink-0 mt-8 h-px border border-solid bg-slate-200 border-slate-200 max-md:max-w-full" />
  );
};

export default Divider;