/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import Divider from './Divider';
import DimensionsForm from './DimensionsForm';

const Popover: React.FC = () => {
  return (
    <main className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <Header />
      <Divider />
      <DimensionsForm />
    </main>
  );
};

export default Popover;