/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface Tag {
  version: string;
}

const tags: Tag[] = [
  { version: 'v1.2.0-beta.50' },
  { version: 'v1.2.0-beta.48' },
  { version: 'v1.2.0-beta.47' },
  { version: 'v1.2.0-beta.46' },
  { version: 'v1.2.0-beta.45' },
  { version: 'v1.2.0-beta.44' },
];

export const TagList: React.FC = () => {
  return (
    <section className="flex flex-col self-center p-4 mt-16 max-w-full text-sm leading-5 whitespace-nowrap bg-white rounded-md border border-solid border-slate-200 text-slate-900 w-[190px] max-md:mt-10">
      <h2 className="font-medium leading-[100%]">Tags</h2>
      {tags.map((tag, index) => (
        <React.Fragment key={tag.version}>
          {index !== 0 && <Divider />}
          <div className={index === 0 ? 'mt-6' : 'mt-2'}>{tag.version}</div>
        </React.Fragment>
      ))}
    </section>
  );
};