/**
 * This code was generated by Builder.io.
 */
import React, { useState } from 'react';
import AccordionItem from './AccordionItem';

interface AccordionData {
  title: string;
  content?: string;
}

const accordionData: AccordionData[] = [
  { title: "Is it accessible" },
  { title: "Is it styled" },
  { title: "Is it animated", content: "Yes. It's animated by default, but you can disable it if you prefer." }
];

const Accordion: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(2);

  const handleToggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="flex flex-col self-center p-6 mt-16 max-w-full bg-white w-[498px] max-md:px-5 max-md:mt-10">
      {accordionData.map((item, index) => (
        <AccordionItem
          key={index}
          title={item.title}
          isOpen={openIndex === index}
          content={item.content}
          onToggle={() => handleToggle(index)}
        />
      ))}
    </div>
  );
};

export default Accordion;