/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface AccordionItemProps {
  title: string;
  isOpen: boolean;
  content?: string;
  onToggle: () => void;
}

const AccordionItem: React.FC<AccordionItemProps> = ({ title, isOpen, content, onToggle }) => {
  return (
    <div className="flex flex-col bg-white">
      <button
        className="flex gap-5 py-4 text-base font-medium bg-white text-slate-900 w-full text-left"
        onClick={onToggle}
        aria-expanded={isOpen}
      >
        <span className="flex-1">{title}</span>
        <img
          src={isOpen ? "https://cdn.builder.io/api/v1/image/assets/TEMP/0cff19dcbe3d5dc0bac9399300cae5d26cae85853128e96c62f7df7e4e740542?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc" : "https://cdn.builder.io/api/v1/image/assets/TEMP/efd475aed0739ae64ef85401fb05aaae92b6a14dc3f68f267c6f9b2d7920581b?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc"}
          alt=""
          className="shrink-0 my-auto w-4 aspect-square"
        />
      </button>
      {isOpen && content && (
        <div className="text-sm leading-5 text-slate-900 pb-4">
          {content}
        </div>
      )}
    </div>
  );
};

export default AccordionItem;