/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ColorPalette from "../ColorPalette/ColorPalette";

const slateColors = [
  { shade: "50", hex: "#f8fafc" },
  { shade: "100", hex: "#f1f5f9" },
  { shade: "200", hex: "#e2e8f0" },
  { shade: "300", hex: "#cbd5e1" },
  { shade: "400", hex: "#94a3b8" },
  { shade: "500", hex: "#64748b" },
  { shade: "600", hex: "#475569" },
  { shade: "700", hex: "#334155" },
  { shade: "800", hex: "#1e293b" },
  { shade: "900", hex: "#0f172a" },
];

const ColorDisplay: React.FC = () => {
  return (
    <main className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <header className="flex gap-5 justify-between max-md:flex-wrap">
        <h1 className="text-3xl font-semibold tracking-tight leading-9 text-slate-900 max-md:max-w-full">
          Colors
        </h1>
        <button className="flex flex-col justify-center text-sm font-medium leading-6 text-white rounded-md">
          <div className="px-3.5 py-2 rounded-md bg-slate-900">View docs</div>
        </button>
      </header>
      <hr className="shrink-0 mt-8 h-px border border-solid bg-slate-200 border-slate-200 max-md:max-w-full" />
      <ColorPalette colorName="Slate" colors={slateColors} />
    </main>
  );
};

export default ColorDisplay;
