/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TabItem {
  label: string;
  imageSrc: string;
  active: boolean;
}

const tabItems: TabItem[] = [
  { label: 'Getting started', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/6d43d15c08dcda56de7c59214f1ec351b6bba4d58f94c2f9672f902f1601af30?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc', active: true },
  { label: 'Components', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/6e1cb93a53db7fdfb5405fff0da1f2bd203bbd72f9d9832d73797187610bc890?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc', active: false },
  { label: 'Documentation', imageSrc: 'https://cdn.builder.io/api/v1/image/assets/TEMP/b19a416600e5147320978bde9fa9a0b951aeb19ad7bfa8ef4e0ec901b0b700c1?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc', active: false },
];

const NavigationTabs: React.FC = () => {
  return (
    <nav className="flex self-center pr-16 mt-16 max-w-full text-sm font-medium leading-5 text-slate-900 w-[499px] max-md:flex-wrap max-md:pr-5 max-md:mt-10">
      {tabItems.map((item, index) => (
        <button
          key={index}
          className={`flex justify-center items-center px-4 py-2 ${
            item.active ? 'bg-slate-100' : 'bg-white'
          }`}
        >
          <div className="flex relative flex-col aspect-[5.9]">
            <img
              loading="lazy"
              src={item.imageSrc}
              alt=""
              className="object-cover absolute inset-0 size-full"
            />
            {item.label}
          </div>
        </button>
      ))}
    </nav>
  );
};

export default NavigationTabs;