/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ContentItem {
  title: string;
  description: string;
}

const contentItems: ContentItem[] = [
  {
    title: 'Introduction',
    description: 'Re-usable components built using Radix UI and Tailwind CSS',
  },
  {
    title: 'Installation',
    description: 'How to install dependencies and structure your app.',
  },
  {
    title: 'Typography',
    description: 'Styles for headings, paragraphs, lists...etc',
  },
];

const NavigationContent: React.FC = () => {
  return (
    <section className="flex flex-col justify-center self-center p-6 mt-2 max-w-full bg-white rounded-md border border-solid shadow-sm border-slate-200 w-[499px] max-md:px-5">
      <div className="max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <aside className="flex flex-col w-[43%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow justify-center max-md:mt-3">
              <div className="flex flex-col px-6 pt-20 pb-6 rounded-md max-md:px-5">
                <div className="shrink-0 mt-5 bg-white rounded-full h-[22px] w-[22px]" />
                <h2 className="mt-5 text-lg font-medium text-white">shadcn/ui</h2>
                <p className="mt-2 text-sm tracking-normal leading-5 text-slate-200">
                  Beautifully designed components built with Radix UI and Tailwind CSS.
                </p>
              </div>
            </div>
          </aside>
          <div className="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow text-sm max-md:mt-3">
              {contentItems.map((item, index) => (
                <div key={index} className="flex flex-col p-3 bg-white rounded-md mt-3 first:mt-0">
                  <h3 className="font-medium text-black leading-[100%]">{item.title}</h3>
                  <p className="mt-1 leading-5 text-slate-500">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default NavigationContent;