/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import NavigationHeader from './NavigationHeader';
import NavigationTabs from './NavigationTabs';
import NavigationContent from './NavigationContent';

const NavigationMenu: React.FC = () => {
  return (
    <main className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <NavigationHeader />
      <hr className="shrink-0 mt-8 h-px border border-solid bg-slate-200 border-slate-200 max-md:max-w-full" />
      <NavigationTabs />
      <NavigationContent />
    </main>
  );
};

export default NavigationMenu;