/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MenuItem {
  label: string;
  shortcut?: string;
  icon?: string;
}

interface DropdownMenuProps {}

const DropdownMenu: React.FC<DropdownMenuProps> = () => {
  const menuItems: MenuItem[] = [
    { label: 'New Tab', shortcut: '⌘T' },
    { label: 'New Window', shortcut: '⌘N' },
    { label: 'New Incognito Window' },
    { label: 'Share', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/db5100762ea4e38a5fd879dcc78eda1920e44d90a03ec4891baec0abce95e756?apiKey=2993ce4605724b1d802a1e90f53966fc&&apiKey=2993ce4605724b1d802a1e90f53966fc' },
    { label: 'Print...', shortcut: '⌘P' },
  ];

  return (
    <div className="flex flex-col self-center px-px mt-1 max-w-full font-medium rounded-md border border-solid shadow-sm border-slate-100 w-[233px]">
      {menuItems.map((item, index) => (
        <div key={index} className="flex flex-col p-1.5 w-full bg-white">
          <div className="flex gap-2 px-2 py-1.5 bg-white">
            <div className="flex-1 text-sm leading-5 text-slate-700">{item.label}</div>
            {item.shortcut && <div className="text-xs leading-5 text-slate-500">{item.shortcut}</div>}
            {item.icon && (
              <img loading="lazy" src={item.icon} alt="" className="shrink-0 my-auto w-4 aspect-square" />
            )}
          </div>
        </div>
      ))}
    </div>
  );
};

export default DropdownMenu;