/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header className="flex gap-5 justify-between max-md:flex-wrap">
      <div className="flex flex-col max-md:max-w-full">
        <h1 className="text-3xl font-semibold tracking-tight leading-9 text-slate-900 max-md:max-w-full">
          Menubar
        </h1>
        <p className="mt-4 text-xl leading-7 text-slate-600 max-md:max-w-full">
          A visually persistent menu common in desktop applications that provides quick access to a consistent set of commands.
        </p>
      </div>
      <div className="flex flex-col justify-center self-start text-sm font-medium leading-6 text-white rounded-md">
        <button className="px-3.5 py-2 rounded-md bg-slate-900">View docs</button>
      </div>
    </header>
  );
};

export default Header;