/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import Divider from './Divider';
import MenuTabs from './MenuTabs';
import DropdownMenu from './DropdownMenu';

const MenubarComponent: React.FC = () => {
  return (
    <div className="flex flex-col px-8 pt-8 pb-16 bg-white max-w-[792px] max-md:px-5">
      <Header />
      <Divider />
      <MenuTabs />
      <DropdownMenu />
    </div>
  );
};

export default MenubarComponent;