/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MenuTabsProps {}

const MenuTabs: React.FC<MenuTabsProps> = () => {
  const tabs = ['File', 'Edit', 'View', 'Profile'];

  return (
    <nav className="flex self-center px-1.5 py-1 mt-16 max-w-full text-sm font-medium leading-5 text-black whitespace-nowrap bg-white rounded-md border border-solid border-slate-300 w-[233px] max-md:mt-10">
      {tabs.map((tab, index) => (
        <button
          key={index}
          className={`px-3 py-1.5 ${tab === 'View' ? 'rounded bg-slate-100' : 'bg-white'}`}
        >
          {tab}
        </button>
      ))}
    </nav>
  );
};

export default MenuTabs;